version: "3"
services:

  phpinfo:
    build: ./
    ports:
      - "18080:80"
    networks:
      - firststepnet
    volumes:
      - .:/var/www/html
    links:
      - mariadb

  mariadb:
    build: ./docker/mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - firststepnet
    environment:
      - MYSQL_DATABASE=firststep
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    ports:
      - 8183:80
    networks:
      - firststepnet
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: userp
      PMA_ARBITRARY: 1

networks:
    firststepnet:
        driver: bridge


